@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InpldXMiLCJpZCI6IjYzN2NlZmIzYTI2NWE5MjNiZWRlNzA3ZCIsImlhdCI6MTY2OTEzMjgxMH0.H72F4grfxjPCwXoDZ5nAFo6ws5J1dah_n1Dmn7VUUEE
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFwcG9sbyIsImlkIjoiNjM3Y2VmYjZhMjY1YTkyM2JlZGU3MDgwIiwiaWF0IjoxNjY5MTMyMzQ4fQ.CtmTa8f_ab_vBJrL9PvTU7xaG4MgYPW91wUkERlduWU

###create blog for user 1
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "ofsdfsdfsdf brian",
  "author": "monty python",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": "not a number"
}

###create blog for user 2
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer {{token2}}

{
  "title": "the  ofsfdsdfsd life",
  "author": "monty python",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": "2"
}

###create blog with invalid header
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer {{token}}

  {
  "title": "the mearnzxczxczxczxcing of life",
  "author": "monty python",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": "2"
}

###create blog with no auth header
POST http://localhost:3003/api/blogs
Content-Type: application/json


  {
  "title": "the mearnzxczxczxczxcing of life",
  "author": "monty python",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": "2"
}

###create blog with wrong auth scheme

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Basic {{token}}

  {
  "title": "the mearnzxczxczxczxcing of life",
  "author": "monty python",
  "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
  "likes": "2"
}

###get blogs for user 1
GET http://localhost:3003/api/blogs
Authorization: Bearer {{token}}

###get blogs for user 2
GET http://localhost:3003/api/blogs
Authorization: Bearer {{token2}}


###delete blog
DELETE http://localhost:3003/api/blogs/637553cbf9f3cdfd544facb8
Authorization: Bearer {{token}}

###update blog likes
PUT http://localhost:3003/api/blogs/637cf397928e5f9034f278f9
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "likes": "1000"
}

###update likes with non castable value
PUT http://localhost:3003/api/blogs/637cf397928e5f9034f278f9
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "likes": "not castable"
}

###update likes without value
PUT http://localhost:3003/api/blogs/637cf397928e5f9034f278f9
Content-Type: application/json
Authorization: Bearer {{token}}

{
 
}

###update likes with null value
PUT http://localhost:3003/api/blogs/637cf397928e5f9034f278f9
Content-Type: application/json
Authorization: Bearer {{token}}

{
 "likes": null
}






###update non updateable path
PUT http://localhost:3003/api/blogs/637cf397928e5f9034f278f9
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "this is fferent"
}


###update blog for different user

PUT http://localhost:3003/api/blogs/637cf397928e5f9034f278f9
Content-Type: application/json
Authorization: Bearer {{token2}}

{
  "likes": 200
}
###update blog with path not in schema


PUT http://localhost:3003/api/blogs/637cf397928e5f9034f278f9
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "this is fferdddent",
  "garbage": "this is garbage"
}

###update blog with invalid token

PUT http://localhost:3003/api/blogs/637cf3a4928e5f9034f27905
Content-Type: application/json
Authorization: Bearer asdfsadfsadfsadfsadfsadf

{
  "title": "this is fferdddent",
  "garbage": "this is garbage"
}

###update blog likes with malformatted id
PUT http://localhost:3003/api/blogs/6
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "likes": "1000"
}







